# Generated by Django 3.2 on 2022-11-04 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0005_keywordmodel_input_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='result_favorite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='musicuploadmodel',
            name='result_favorite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicuploadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
