# Generated by Django 3.2 on 2022-11-04 07:36
from django.shortcuts import HttpResponse
from django.shortcuts import render
from django.views import *
from django.contrib import admin
from django.db import migrations, models
from django.views import csrf
from django.urls import base


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_keywordmodel_input_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='ImageUploadModel',
            name='image',
            field=models.ImageField(null=True, upload_to='appname'),
        ),
    ]
