# Generated by Django 3.2 on 2022-11-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_imageuploadmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='image',
        ),
    ]
