# Generated by Django 3.2 on 2022-11-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20221104_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagekeywordmodel',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='imagekeywordmodel',
            old_name='keyword_id',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='musickeywordmodel',
            old_name='keyword_id',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='musickeywordmodel',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='musicuploadmodel',
            name='keyword',
        ),
    ]
