# Generated by Django 3.2 on 2022-11-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_img_mon_samplekeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
