# Generated by Django 3.2 on 2022-11-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_imageuploadmodel_result_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagekeywordmodel',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='imagekeywordmodel',
            old_name='keyword_id',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='musickeywordmodel',
            old_name='keyword_id',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='musickeywordmodel',
            old_name='music_id',
            new_name='music',
        ),
    ]
