# Generated by Django 3.2 on 2022-11-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20221116_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='artuploadmodel',
            name='like_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
