# Generated by Django 3.2 on 2022-11-07 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_mediafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mediafile',
        ),
        migrations.AddField(
            model_name='img_mon',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='img_mon',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
