# Generated by Django 3.2 on 2022-11-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0009_auto_20221116_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artkeywordmodel',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.artuploadmodel'),
        ),
        migrations.AlterField(
            model_name='artkeywordmodel',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.keywordmodel'),
        ),
        migrations.AlterField(
            model_name='artuploadmodel',
            name='result_favorite',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artuploadmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keywordmodel',
            name='word',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
