# Generated by Django 3.2 on 2022-11-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20221109_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagekeywordmodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='salon.imageuploadmodel'),
        ),
    ]
