# Generated by Django 3.2 on 2022-11-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_auto_20221111_1149'),
        ('salon', '0010_alter_imagekeywordmodel_image'),
    ]

    operations = [
    ]
