# Generated by Django 3.2 on 2022-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_auto_20221122_1357'),
        ('salon', '0010_autoartuploadmodel'),
    ]

    operations = [
    ]
