# Generated by Django 3.2 on 2022-11-25 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0011_merge_0010_auto_20221122_1357_0010_autoartuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artkeywordmodel',
            name='art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.artuploadmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artkeywordmodel',
            name='keyword',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.keywordmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artuploadmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
