# Generated by Django 3.2 on 2022-11-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_auto_20221125_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='artuploadmodel',
            name='like_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
